version: "2"
services: 
  web:
    container_name: app
    build: .
    volumes: 
      - ./:/app
    ports:
      - "4000:4000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"      